- README.md
And also improved the example.
> Added README buttons

- src/Nakadi/EventTypes.hs
- src/Nakadi/Internal/Util.hs
- src/Nakadi/Types/Service.hs
> Cleanup some code

- .travis.yml
- README.md
- package.yaml
- src/Network/Nakadi/EventTypes/Partitions.hs
- src/Network/Nakadi/Internal/Http.hs
- src/Network/Nakadi/Internal/Types/Exceptions.hs
- src/Network/Nakadi/Internal/Types/Service.hs
- src/Network/Nakadi/Types/Service.hs
- tests/Network/Nakadi/EventTypes/Test.hs
- tests/Tests.hs
> Start test suite

- package.yaml
- src/Network/Nakadi/Internal/Lenses.hs
> Disable Haddock generation for lenses as workaround for Haddock bug.

- src/Network/Nakadi/Internal/Lenses.hs
- src/Network/Nakadi/Internal/Types/Service.hs
- src/Network/Nakadi/Subscriptions/Events.hs
- tests/Network/Nakadi/EventTypes/Test.hs
- tests/Network/Nakadi/Tests/Common.hs
Added flowId field parsing to the MetadataEnriched;
Added test for flowId parsing;
Removed unused imports to prevent compiler warnings;
> FlowId parsing in MetadataEnriched

- .gitignore
- src/Network/Nakadi/Subscriptions/Events.hs
> fixed the type parameters for `runSubscriptionR`

- src/Network/Nakadi/Types/Subscription.hs
@etorreborre @mtesseract Let's discuss
> Exposed the constructor for the subscription stream context

- src/Network/Nakadi/Internal/Types/Config.hs
- src/Network/Nakadi/Internal/Types/Exceptions.hs
- src/Network/Nakadi/Internal/Types/Problem.hs
- src/Network/Nakadi/Internal/Types/Service.hs
- src/Network/Nakadi/Internal/Types/Subscription.hs
fixes #42. I think this is the right thing to do
> Use StrictData for all the data types

- src/Network/Nakadi/Internal/Types/Service.hs
@vitold, are you fine with this?
(also adding @etorreborre @amrhassan)
> Use PartitionName type instead of Text

- AUTHORS.md
Release preperations. Is this ok?
@etorreborre @amrhassan @vitold 
Feel free to suggest modifications.
> Added AUTHORS file

- src/Network/Nakadi/Internal/Types/Service.hs
- tests/Network/Nakadi/EventTypes/CursorsLag/Test.hs
- tests/Network/Nakadi/EventTypes/ShiftedCursors/Test.hs
- tests/Network/Nakadi/EventTypes/Test.hs
- tests/Network/Nakadi/Tests/Common.hs
@vitold @etorreborre @amrhassan 
More type safety.
> Use EventId instead of Text

- package.yaml
- src/Network/Nakadi/Config.hs
- src/Network/Nakadi/Internal/Http.hs
- src/Network/Nakadi/Internal/Retry.hs
- src/Network/Nakadi/Internal/Types/Config.hs
- tests/Network/Nakadi/Internal/Retry/Test.hs
- tests/Network/Nakadi/Internal/Test.hs
- tests/Tests.hs
This implements callback support for HTTP errors (#35).
@etorreborre @vitold @amrhassan
> Http error callback

- package.yaml
- stack.yaml
Version bump, move tasty dependency to test section.
> Version bump

- stack.yaml
> Upgrade to LTS 10.5

- package.yaml
- src/Network/Nakadi/Prelude.hs
> Add Prelude module

- src/Network/Nakadi/Config.hs
- src/Network/Nakadi/EventTypes.hs
- src/Network/Nakadi/EventTypes/CursorsLag.hs
- src/Network/Nakadi/EventTypes/EventType.hs
- src/Network/Nakadi/EventTypes/Events.hs
- src/Network/Nakadi/EventTypes/Partitions.hs
- src/Network/Nakadi/EventTypes/ShiftedCursors.hs
- src/Network/Nakadi/Internal/Config.hs
- src/Network/Nakadi/Internal/Http.hs
- src/Network/Nakadi/Internal/Types/Config.hs
- src/Network/Nakadi/Internal/Types/Service.hs
- src/Network/Nakadi/Subscriptions/Events.hs
- tests/Network/Nakadi/EventTypes/CursorsLag/Test.hs
- tests/Network/Nakadi/EventTypes/ShiftedCursors/Test.hs
- tests/Network/Nakadi/EventTypes/Test.hs
- tests/Network/Nakadi/Examples/Echo/Echo.hs
- tests/Network/Nakadi/Examples/Echo/Test.hs
- tests/Network/Nakadi/Internal/Http/Test.hs
- tests/Network/Nakadi/Tests/Common.hs
Add FlowId to all requests that expect a X-Flow-Id header as documented at
https://zalando.github.io/nakadi/manual.html
New function: setFlowId.
> Include FlowIds to all requests that accept X-Flow-Id header

- AUTHORS.md
- package.yaml
Schulte → Clasmeier in hpack yaml and in authors list
> Fix copyright notice

- package.yaml
Apparently we need more version bounds for building via cabal.
This time I have tested building using a cabal sandbox.
> Fix cabal build

- package.yaml
- src/Network/Nakadi/Internal/Types.hs
> Added a MonadLoggerIO instance for NakadiT

- brittany.yaml
- src/Network/Nakadi/Internal/Types/Util.hs
- src/Network/Nakadi/Subscriptions.hs
- tests/Network/Nakadi/EventTypes/Test.hs
- tests/Network/Nakadi/Examples/Subscription/Test.hs
- tests/Network/Nakadi/Subscriptions/Processing/Test.hs
- tests/Network/Nakadi/Subscriptions/Test.hs
This PR contains no changes of semantics.
Just brittany reformatting and some hlint improvements (removed unused pragmas and unnecessary `do`s).
Could somebody review this? :-)
@etorreborre @erthalion
This will simplify follow-up PRs significantly.
Thanks!
> Reformat some files using brittany, include brittany specification

- CHANGES.md
> Added Change Log

- src/Network/Nakadi/Internal/Unsafe/IO.hs
- src/Network/Nakadi/Unsafe/IO.hs
- tests/Network/Nakadi/MonadicAPI/Test.hs
I think one useful piece was missing here: `modifyGlobalConfiguration`.
Furthermore, I have added some comments and clarified that this API is experimental.
> Implement modifyGlobalConfiguration and added Haddock comments

- CHANGES.md
- src/Network/Nakadi/Config.hs
- src/Network/Nakadi/EventTypes.hs
- src/Network/Nakadi/EventTypes/CursorsLag.hs
- src/Network/Nakadi/EventTypes/EventType.hs
- src/Network/Nakadi/EventTypes/Events.hs
- src/Network/Nakadi/EventTypes/Partitions.hs
- src/Network/Nakadi/EventTypes/ShiftedCursors.hs
- src/Network/Nakadi/Internal/Http.hs
- src/Network/Nakadi/Internal/TH.hs
- src/Network/Nakadi/Internal/Types.hs
- src/Network/Nakadi/Internal/Types/Service.hs
- src/Network/Nakadi/Internal/Util.hs
- src/Network/Nakadi/Subscriptions.hs
- src/Network/Nakadi/Subscriptions/Cursors.hs
- src/Network/Nakadi/Subscriptions/Events.hs
- src/Network/Nakadi/Types/Problem.hs
- tests/Network/Nakadi/Config/Test.hs
- tests/Network/Nakadi/EventTypes/BusinessEvents/Test.hs
- tests/Network/Nakadi/EventTypes/CursorsLag/Test.hs
- tests/Network/Nakadi/EventTypes/ShiftedCursors/Test.hs
- tests/Network/Nakadi/EventTypes/Test.hs
- tests/Network/Nakadi/Examples/Subscription/Test.hs
- tests/Network/Nakadi/Internal/Http/Test.hs
- tests/Network/Nakadi/Registry/Test.hs
- tests/Network/Nakadi/Subscriptions/Processing/Test.hs
- tests/Network/Nakadi/Subscriptions/Stats/Test.hs
- tests/Network/Nakadi/Subscriptions/Test.hs
- tests/Network/Nakadi/Tests/Common.hs
This PR contains:
* Several code improvements suggested by HLint (this is the preparation for HLint integration as part of the Travis pipeline).
* Support for GHC 8.4.3 / Stackage LTS-12. This required an implementation for the new method `generalBracket`.
* Versions for `base` fixed and unused dependency removed (`lifted-async`).
* Unfortunately this also includes a lot of code reformatting due to Brittany.
Besides that, no actual code changes.
> HLint Improvements & Support for GHC 8.4.3

- AUTHORS.md
> Update AUTHORS.md file

- .travis.yml
- src/Network/Nakadi/Internal/Committer/TimeBuffer.hs
* Fix indentation, otherwise downstream code uses the library won't be able to create local hoogle db
* Add additional step to run `stack haddock` to CI script
> Fixes haddock building
